#!/bin/bash

# Formatting
label="$(tput setaf 7;tput bold)"
reset="$(tput sgr0)"
red="$(tput setaf 1;tput bold)"
yellow="$(tput setaf 3;tput bold)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
green="$(tput setaf 2)"

l(){
	echo "$label${1}$reset"
}

y() {
	echo "$yellow${1}$reset"
}

m() {
	echo "$magenta${1}$reset"
}

c() {
	echo "$cyan${1}$reset"
}

g() {
	echo "$green${1}$reset"
}


# Function to calculate the greatest common divisor (GCD)
gcd() {
  local a=$1
  local b=$2
  while [[ $b -ne 0 ]]; do
    local temp=$b
    b=$((a % b))
    a=$temp
  done
  echo $a
}

# Function to calculate the aspect ratio
aspect_ratio() {
  local ratio=$1
  local width=$2
  local height=$3
  
  # Check if ratio is in the format "x:y"
  if [[ $ratio == *":"* ]]; then
    local ratio_w=$(cut -d ":" -f 1 <<< $ratio)
    local ratio_h=$(cut -d ":" -f 2 <<< $ratio)
    
    # Calculate the value of "x" or "y" depending on which one is missing
    if [[ $width == "x" ]]; then
      local ratio_x=$((height * ratio_w / ratio_h))
      echo "x: $ratio_x"
    elif [[ $height == "x" ]]; then
      local ratio_x=$((width * ratio_h / ratio_w))
      echo "x: $ratio_x"
    else
      echo "Invalid input format!"
      exit 1
    fi
  else
    echo "Invalid input format!"
    exit 1
  fi
}

# Check if the help option is specified
if [[ $1 == "-h" || $1 == "--h" ]]; then
  echo
  echo "         $(y "ARA - The Aspect Ratio Calculator")"
  echo "      ————————————————————————————————————————"
  echo "      ARA solves for $(l "x"). Put the $(l "x") where you"
  echo "      want the value for $(l "x") to be calculated."
  echo
  echo "      $(y "Usage:") $(l "ara") $(m "<ratio>") $(c "<width>") $(g "<height>")"
  echo
  echo "      $(y "Example 1") $(l "ara") $(m "16:9") $(c "1024") $(g "x")"
  echo "      $(y "Example 2:") $(l "ara") $(m "16:9") $(c "x") $(g "576")"
  echo
  exit 0
fi

# Parse command-line arguments
if [[ $# -eq 2 ]]; then
  aspect_ratio $1 $2 "x"
elif [[ $# -eq 3 ]]; then
  aspect_ratio $1 $2 $3
else
  echo "I'd appreciate input."
  echo
  echo "Usage: ara <ratio> <width> <height>"
  echo "Example: ara 16:9 1024 x"
  exit 1
fi
